package com.devsync.activity.entity;

/**
 * Every tracked event inside DevSync. Stored as an enum (never as a free-form string)
 * so the timeline can be filtered and grouped reliably.
 */
public enum ActivityType {
    PROJECT_CREATED, PROJECT_UPDATED, PROJECT_ARCHIVED, PROJECT_RESTORED, PROJECT_DELETED,
    USER_JOINED_PROJECT, USER_LEFT_PROJECT,
    TASK_CREATED, TASK_ASSIGNED, TASK_UPDATED, TASK_MOVED, TASK_COMPLETED, TASK_DELETED,
    TASK_STARTED, BRANCH_CREATED,
    PR_OPENED, PR_UPDATED, PR_APPROVED, PR_CHANGES_REQUESTED, PR_MERGED, PR_CLOSED,
    MESSAGE_SENT, POST_CREATED, COMMENT_ADDED, FILE_UPLOADED,
    ROLE_CHANGED, USER_BLOCKED, USER_UNBLOCKED,
    INVITATION_SENT, INVITATION_ACCEPTED, INVITATION_DECLINED,
    JOIN_REQUESTED, JOIN_APPROVED, JOIN_REJECTED,
    PROJECT_VISIBILITY_CHANGED, MEMBER_ROLE_CHANGED, OWNERSHIP_TRANSFERRED,
    REPORT_RESOLVED, REPORT_REJECTED
}
