/* eslint-disable */
/**
 * Generated API types.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.22.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as auth from "../auth.js";
import type * as bookmarks from "../bookmarks.js";
import type * as posts from "../posts.js";
import type * as projects from "../projects.js";
import type * as search from "../search.js";
import type * as teams from "../teams.js";
import type * as users from "../users.js";
import type * as usersInternal from "../usersInternal.js";
import type { FilterFunction } from "convex/server";

declare module "convex/server" {
  interface Modules {
    auth: typeof auth;
    bookmarks: typeof bookmarks;
    posts: typeof posts;
    projects: typeof projects;
    search: typeof search;
    teams: typeof teams;
    users: typeof users;
    usersInternal: typeof usersInternal;
  }
}

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: any;

/**
 * A utility for referencing Convex internal functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: any;
