/* eslint-disable */
/**
 * Generated server utilities.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.22.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ActionBuilder,
  DatabaseReader,
  DatabaseWriter,
  HttpActionBuilder,
  MutationBuilder,
  QueryBuilder,
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
  GenericDatabaseReader,
  GenericDatabaseWriter,
} from "convex/server";
import type { DataModel } from "./dataModel.js";

/**
 * Define a mutation in this Convex app's API.
 *
 * Usage:
 *
 * ```ts
 * import { mutation } from "../_generated/server.js";
 * import { v } from "convex/values";
 * ```
 */
export declare const mutation: MutationBuilder<DataModel, "public">;
export declare const query: QueryBuilder<DataModel, "public">;
export declare const action: ActionBuilder<DataModel, "public">;
export declare const httpAction: HttpActionBuilder;

/**
 * Used in internal Convex functions (mutations, queries, actions) that
 * should not be callable from the client.
 */
export declare const internalMutation: MutationBuilder<DataModel, "internal">;
export declare const internalQuery: QueryBuilder<DataModel, "internal">;
export declare const internalAction: ActionBuilder<DataModel, "internal">;

/**
 * A set of services for use within Convex query functions.
 *
 * The query context is passed as the first argument to any Convex query
 * function run on the server.
 *
 * This differs from the `QueryCtx` type used for `query` functions.
 */
export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;

export type DatabaseReader = GenericDatabaseReader<DataModel>;
export type DatabaseWriter = GenericDatabaseWriter<DataModel>;
